version: "3.8"
volumes:
  build_folder: null

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/frontend
    command: "yarn start"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/:/backend
    command: "npm start"
